AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hue API Lambda function template

Parameters:
  BridgeIP:
    Type: String
    Description: "IP address of the Hue Bridge"
  HueUsername:
    Type: String
    Description: "Username for the Hue Bridge API"

Resources:
  HueLightingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: .
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          BRIDGE_IP: !Ref BridgeIP
          HUE_USERNAME: !Ref HueUsername
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Principal: apigateway.amazonaws.com
              Resource: arn:aws:lambda:<YOUR_REGION>:<YOUR_ACCOUNT_ID>:function:<LAMBDA_FUNCTION_NAME>
